const columnsConfig = [
  { field: "manoiya", headerName: "מנועיה", isEdit: true, type: "singleSelect", valueOptions: manoiyaOptions },
  { field: "hatakType", headerName: 'סוג חט"כ', isEdit: true, type: "singleSelect", valueOptions: hatakTypeOptions },
  { field: "sendingDivision", headerName: "אוגדה מוסרת", isEdit: true, type: "singleSelect", valueOptions: ogdotOptions },
  { field: "sendingBrigade", headerName: "חטיבה מוסרת", isEdit: true, type: "string" },
  { field: "sendingBattalion", headerName: "גדוד מוסר", isEdit: true, type: "string" },
  { field: "zadik", headerName: "צ' של כלי", isEdit: true, type: "string" },
  { field: "reciveDate", headerName: "תאריך קבלה", isEdit: true, type: "date" },
  { field: "engineSerial", headerName: "מספר מנוע", isEdit: false },
  { field: "minseretSerial", headerName: "מספר ממסרת", isEdit: true, type: "string" },
  { field: "hatakStatus", headerName: 'סטטוס חט"כ', isEdit: true, type: "singleSelect", valueOptions: hatakStatusOptions },
  { field: "tipulType", headerName: "סוג טיפול", isEdit: true, type: "singleSelect", valueOptions: ["שבר", 'שע"מ'] },
  { field: "waitingHHType", headerName: 'סוג ח"ח ממתין', isEdit: true, isMultiSelect: true, valueOptions: waitingHHTypeOptions },
  { field: "recivingDivision", headerName: "אוגדה מקבלת", isEdit: true, type: "singleSelect", valueOptions: ogdotOptions },
  { field: "recivingBrigade", headerName: "חטיבה מקבלת", isEdit: true, type: "string" },
  { field: "recivingBattalion", headerName: "גדוד מקבל", isEdit: true, type: "string" },
  { field: "startWorkingDate", headerName: "תאריך לפקודה", isEdit: true, type: "date" },
  { field: "forManoiya", headerName: "מנועיה לפקודה", isEdit: true, type: "singleSelect", valueOptions: manoiyaOptions },
  { field: "performenceExpectation", headerName: "צפי ביצוע", isEdit: true, type: "singleSelect", valueOptions: performenceExpectationOptions },
  { field: "intended", headerName: "מיועד ל?", isEdit: true, type: "singleSelect", valueOptions: intendedOptions },
];{ field: "engineSerial", headerName: "מספר מנוע", isEdit: false },
  { field: "minseretSerial", headerName: "מספר ממסרת", isEdit: true, type: "string" },