// Field name translations (Hebrew)
export const fieldTranslations = {
  manoiya: "מנועיה",
  hatakType: 'סוג חט"כ',
  sendingDivision: "אוגדה מוסרת",
  sendingBrigade: "חטיבה מוסרת",
  sendingBattalion: "גדוד מוסר",
  zadik: "צ' של כלי",
  reciveDate: "תאריך קבלה",
  engineSerial: "מספר מנוע",
  minseretSerial: "מספר ממסרת",
  hatakStatus: 'סטטוס חט"כ',
  tipulType: 'סוג טיפול',
  problem: "פירוט תקלה",
  waitingHHType: 'סוג ח"ח ממתין',
  recivingDivision: "אוגדה מקבלת",
  recivingBrigade: "חטיבה מקבלת",
  recivingBattalion: "גדוד מקבל",
  startWorkingDate: "תאריך לפקודה",
  forManoiya: "מנועיה לפקודה",
  performenceExpectation: "צפי ביצוע",
  detailsOfNonCompliance: "פירוט אי עמידה",
  intended: "מיועד ל?",
  pca: 'פק"ע',
  shinoa: "שינוע",
  detailsHH: 'פירוט ח"ח',
  shamEngine: 'שע"מ מנוע',
  shamMinseret: 'שע"מ ממסרת',
  actuallyChecked: "מה נבדק בפועל",
  outgoingEngine: "מנוע יוצא",
  shamOutgoingEngine: 'שע"מ מנוע יוצא',
  outgoingMinseret: "ממסרת יוצאת",
  shamOutgoingMinseret: 'שע"מ ממסרת יוצאת',
  engineFaultBank: "בנק תקלות מנוע",
  minseretFaultBank: "בנק תקלות ממסרת",
  engineDeactivationNumber: "מספר השבתה מנוע",
  minseretDeactivationNumber: "מספר השבתה ממסרת",
  goingToBeDeleted: "נמחק",
}

// Status translations
export const statusTranslations = {
  Pending: 'ממתין',
  'In Progress': 'בטיפול',
  Completed: 'הושלם',
  Cancelled: 'בוטל',
  'Waiting for Parts': 'ממתין לחלקים',
  'Ready for Pickup': 'מוכן לאיסוף',
};
